# Generated by Django 5.2.4 on 2025-07-11 15:43

import django.db.models.deletion
import itineraries.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='行程標題', max_length=200)),
                ('description', models.TextField(help_text='行程描述')),
                ('start_date', models.DateField(help_text='行程開始日期')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.journey')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='ItineraryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(help_text='行程圖片', upload_to=itineraries.models.itinerary_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='圖片說明', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Itinerary Photo',
                'verbose_name_plural': 'Itinerary Photos',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='地點名稱', max_length=100)),
                ('description', models.TextField(blank=True, help_text='地點描述', null=True)),
                ('latitude', models.FloatField(help_text='緯度')),
                ('longitude', models.FloatField(help_text='經度')),
                ('order', models.PositiveIntegerField(default=0, help_text='在行程中的順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(help_text='地點圖片', upload_to=itineraries.models.location_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='圖片說明', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.location')),
            ],
            options={
                'verbose_name': 'Location Photo',
                'verbose_name_plural': 'Location Photos',
            },
        ),
    ]
