# Generated by Django 5.2.4 on 2025-07-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': '行程', 'verbose_name_plural': '行程列表'},
        ),
        migrations.AlterModelOptions(
            name='itineraryphoto',
            options={'verbose_name': '行程照片', 'verbose_name_plural': '行程照片列表'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order'], 'verbose_name': '地點', 'verbose_name_plural': '地點列表'},
        ),
        migrations.AlterModelOptions(
            name='locationphoto',
            options={'verbose_name': '地點照片', 'verbose_name_plural': '地點照片列表'},
        ),
    ]
