# Generated by Django 5.2.4 on 2025-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_alter_itinerary_options_alter_itineraryphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps 地點清單網址 (例如: https://maps.app.goo.gl/...)', null=True),
        ),
    ]
