# Generated by Django 5.2.4 on 2025-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itinerary_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='google_maps_urls',
            field=models.TextField(blank=True, help_text='Google Maps 景點網址列表，每行一個網址', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='地址', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps 地點網址', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='place_types',
            field=models.CharField(blank=True, help_text='地點類型', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(blank=True, help_text='評分', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='地點名稱', max_length=200),
        ),
    ]
