# Generated by Django 5.2.4 on 2025-07-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_remove_itinerary_google_maps_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='google_maps_urls',
        ),
    ]
