# Generated by Django 5.2.4 on 2025-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_remove_itinerary_google_maps_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, help_text='地點描述', max_length=300, null=True),
        ),
    ]
