# Generated by Django 5.2.4 on 2025-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_alter_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.CharField(help_text='行程描述', max_length=300),
        ),
    ]
