# Generated by Django 5.2.4 on 2025-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_alter_itinerary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_maps_url',
            field=models.CharField(blank=True, help_text='Google Maps 地點網址', max_length=1000, null=True),
        ),
    ]
