# Generated by Django 5.2.4 on 2025-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='arrived_hour',
            field=models.IntegerField(blank=True, help_text='到達小時 (0-23)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='arrived_minute',
            field=models.IntegerField(blank=True, help_text='到達分鐘 (0-59)', null=True),
        ),
    ]
