# Generated by Django 5.2.4 on 2025-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_location_arrived_hour_location_arrived_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='departure_hour',
            field=models.IntegerField(blank=True, help_text='離開小時 (0-23)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='departure_minute',
            field=models.IntegerField(blank=True, help_text='離開分鐘 (0-59)', null=True),
        ),
    ]