# Generated by Django 5.2.4 on 2025-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_location_departure_hour_location_departure_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('morning', '上午'), ('afternoon', '下午'), ('evening', '晚上')], default='morning', help_text="時間段 (例如: '上午', '下午', '晚上')", max_length=50),
        ),
    ]
