version: "3.8"

services:
  django:
    build: .
    container_name: hina-travel-diary-django
    command: sh -c "python manage.py collectstatic --noinput && gunicorn RAGPilot.wsgi:application --bind 0.0.0.0:8080 --workers 3"
    expose:
      - 8080
    ports:
      - "8000:8000"
    volumes:
      - ${MEDIA_DIR:-./media}:/app/media
      - ${SQLITE_DB:-./db.sqlite3}:/app/db.sqlite3
    working_dir: /app
    restart: unless-stopped
