version: "3.8"

services:
  django:
    build: .
    container_name: hina-travel-diary-django
    command: sh -c "python manage.py collectstatic --noinput && gunicorn HinaTravelDiary.wsgi:application --bind 0.0.0.0:8080 --workers 3 --reload"
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ${MEDIA_DIR:-./media}:/app/media
      - ${SQLITE_DB:-./db.sqlite3}:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - .:/app
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    container_name: hina-travel-diary-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${MEDIA_DIR:-./media}:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - django
