# Generated by Django 5.2.4 on 2025-07-11 15:43

import django.db.models.deletion
import journeys.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='國家名稱', max_length=100, unique=True)),
                ('english_name', models.CharField(help_text='國家英文名稱', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_highlighted', models.BooleanField(default=False, help_text='是否為精選旅程')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.country')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
            },
        ),
        migrations.CreateModel(
            name='JourneyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=journeys.models.journey_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='説明圖片內容', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journeys.journey')),
            ],
            options={
                'verbose_name': 'Journey Photo',
                'verbose_name_plural': 'Journey Photos',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='城市名稱', max_length=100)),
                ('english_name', models.CharField(help_text='城市英文名稱', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='journeys.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'unique_together': {('country', 'name')},
            },
        ),
    ]
