# Generated by Django 5.2.4 on 2025-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市列表'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '國家', 'verbose_name_plural': '國家列表'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': '旅程', 'verbose_name_plural': '旅程列表'},
        ),
        migrations.AlterModelOptions(
            name='journeyphoto',
            options={'verbose_name': '旅程照片', 'verbose_name_plural': '旅程照片列表'},
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='test', help_text='國家代碼', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(help_text='國家英文名稱', max_length=100, unique=True),
        ),
    ]
