# Generated by Django 5.2.4 on 2025-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='是否為精選國家'),
        ),
    ]
