# Generated by Django 5.2.4 on 2025-07-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_country_is_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.city'),
        ),
    ]
